name: sauda_line
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  collection: 1.17.2
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  equatable: 2.0.5
  file_picker: 6.1.1
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  flutter_plugin_android_lifecycle: 2.0.17
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  image_picker: 1.0.4
  image_picker_android: 0.8.8
  image_picker_for_web: 3.0.1
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: 2.9.1
  infinite_scroll_pagination: 4.0.0
  intl: 0.18.1
  json_path: 0.6.2
  mask_text_input_formatter: 2.4.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.6
  provider: 6.0.5
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: ^6.1.14
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  video_player: 2.8.1
  video_player_android: 2.4.10
  video_player_avfoundation: 2.5.1
  video_player_platform_interface: 6.2.1
  video_player_web: 2.1.2
  webview_flutter: ^4.0.7
  webview_flutter_android: 3.3.1
  webview_flutter_platform_interface: 2.0.2
  webview_flutter_wkwebview: 3.1.1
  webviewx_plus: 0.3.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  simple_barcode_scanner: ^0.0.8
  persistent_bottom_nav_bar_v2: ^4.2.8
  http: ^0.13.6
  easy_splash_screen: ^1.0.4
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  flutter_localization: ^0.1.14
  pagination_flutter: ^0.0.8
  listview_infinite_pagination: ^0.0.14
  flutter_quill: ^7.7.0
  vsc_quill_delta_to_html: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_html: ^3.0.0-beta.2


dev_dependencies:
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0

  flutter_test:
    sdk: flutter



flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.jpg'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Thin.ttf
        - asset: assets/fonts/Gilroy/Gilroy-UltraLight.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Semibold.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Extrabold.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Heavy.ttf
    - family: Bebas
      fonts:
        - asset: assets/fonts/Bebas/Bebas_Regular.otf
        - asset: assets/fonts/Bebas/Bebas_Bold.otf
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-Bold.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-BoldItalic.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-Demi.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-DemiItalic.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-Heavy.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-HeavyItalic.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-Italic.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-LightItalic.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-Medium.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-MediumItalic.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-Regular.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-Thin.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-ThinItalic.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-UltraLight.ttf
        - asset: assets/fonts/AvenirNextCyr/AvenirNextCyr-UltraLightIt.ttf
    - family: Atyp
      fonts:
        - asset: assets/fonts/Atyp/Atyp.ttf
    - family: Futura
      fonts:
        - asset: assets/fonts/futura/FuturaPT-Bold.ttf
        - asset: assets/fonts/futura/FuturaPT-Book.ttf
        - asset: assets/fonts/futura/FuturaPT-Demi.ttf
        - asset: assets/fonts/futura/FuturaPT-ExtraBold.ttf
        - asset: assets/fonts/futura/FuturaPT-Heavy.ttf
        - asset: assets/fonts/futura/FuturaPT-Light.ttf
        - asset: assets/fonts/futura/FuturaPT-Medium.ttf
        - asset: assets/fonts/futura/FuturaPT-Bold.ttf
        - asset: assets/fonts/futura/FuturaPT-Bold.ttf
        - asset: assets/fonts/futura/FuturaPT-Bold.ttf
        - asset: assets/fonts/futura/FuturaPT-Bold.ttf
        - asset: assets/fonts/futura/FuturaPT-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

